language: c++
compiler:
    - gcc

only:
    - ci

before_script:
    - chmod +x .travis-scripts/before-install-sfml.sh

install:
    - .travis-scripts/before-install-sfml.sh

script: cmake . && make

